apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      enabled: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    namespace: external-secrets
    name: in-cluster
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: "2.5.0"
    chart: external-secrets
