apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: default
  syncPolicy:
    # automated:
      # prune: false
      # selfHeal: false
    syncOptions:
      - RespectIgnoreDifferences=true
  destination:
    namespace: keda
    name: in-cluster
  source:
    repoURL: https://kedacore.github.io/charts
    targetRevision: "2.13.1"
    chart: keda
