apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: kyverno
spec:
  project: default
  ignoreDifferences:
  - group: '*'
    kind: Service
    jqPathExpressions:
      - '.spec.ports[]?.nodePort'
#    jsonPointers:
#    - /spec/ports/[]/nodePort
  syncPolicy:
    # automated:
      # prune: false
      # selfHeal: false
    syncOptions:
      - RespectIgnoreDifferences=true
  destination:
    namespace: kyverno
    name: in-cluster
  source:
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: "3.3.2"
    chart: kyverno
