apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
  - group: '*'
    kind: Service
    jqPathExpressions:
      - '.spec.ports[]?.nodePort'
#    jsonPointers:
#    - /spec/ports/[]/nodePort
  syncPolicy:
    # automated:
      # prune: false
      # selfHeal: false
    syncOptions:
      - RespectIgnoreDifferences=true
  destination:
    namespace: metrics
    name: in-cluster
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: "3.8.2"
    chart: metrics-server
    helm:
      values: |
         args:
           - --kubelet-insecure-tls
