apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-crd
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
  - group: '*'
    kind: Service
    jqPathExpressions:
      - '.spec.ports[]?.nodePort'
#    jsonPointers:
#    - /spec/ports/[]/nodePort
  syncPolicy:
    # automated:
      # prune: false
      # selfHeal: false
    syncOptions:
      - RespectIgnoreDifferences=true
  destination:
    namespace: monitoring
    name: in-cluster
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "15.0.0"
    chart: prometheus-operator-crds
